---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cuxe8137/cv.claramauro.fr
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH