name: Build and deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build & export static site
        run: npm run build

      - name: Copy .htaccess to ./dist
        run: cp .htaccess ./dist/

      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{secrets.FTP_SERVER}}
          username: ${{secrets.FTP_USERNAME}}
          password: ${{secrets.FTP_PASSWORD}}
          protocol: ftps
          local-dir: ./dist/
          server-dir: ./
          dangerous-clean-slate: true

